/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class XPress_DatabaseExecutor_LibXML2ExecutorLow */

#ifndef _Included_XPress_DatabaseExecutor_LibXML2ExecutorLow
#define _Included_XPress_DatabaseExecutor_LibXML2ExecutorLow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     XPress_DatabaseExecutor_LibXML2ExecutorLow
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_XPress_DatabaseExecutor_LibXML2ExecutorLow_execute
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
