package XTest.XPathGeneration.LogicTree.InfomationTree.InformationTreeFunctionNode.InformationTreeDirectContentFunctionNode;

import XTest.XPathGeneration.LogicTree.InfomationTree.InformationTreeFunctionNode.InformationTreeFunctionNode;

public abstract class InformationTreeDirectContentFunctionNode extends InformationTreeFunctionNode {
    public abstract String getCurrentLevelCalculationString();
}
